<center>
<img src="../../img/ods_stickers.jpg" />
    
## [mlcourse.ai](mlcourse.ai) â€“ Open Machine Learning Course 
Author: Arina Lopukhova (@erynn). Edited by [Yury Kashnitskiy](https://yorko.github.io) (@yorko). This material is subject to the terms and conditions of the [Creative Commons CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license. Free use is permitted for any non-commercial purpose.

<h1><center>Assignment #1. Fall 2018</center></h1>
<h2><center>Exploratory data analysis of Olympic games with Pandas</center></h2>

__There are ten questions about [120 years of Olympic history: athletes and results](https://www.kaggle.com/heesoo37/120-years-of-olympic-history-athletes-and-results/version/2) dataset in this task. Your task is to fill in the missing Python code and choose answers in [this web-form](https://docs.google.com/forms/d/179HYvlF_0x435CWdu2aOtR9a3flh0YCQXXNXhXaKw2M).__

Download the file `athlete_events.csv` from [Kaggle page](https://www.kaggle.com/heesoo37/120-years-of-olympic-history-athletes-and-results). The dataset has the following features (copied from Kaggle):

- __ID__ - Unique number for each athlete
- __Name__ - Athlete's name
- __Sex__ - M or F
- __Age__ - Integer
- __Height__ - In centimeters
- __Weight__ - In kilograms
- __Team__ - Team name
- __NOC__ - National Olympic Committee 3-letter code
- __Games__ - Year and season
- __Year__ - Integer
- __Season__ - Summer or Winter
- __City__ - Host city
- __Sport__ - Sport
- __Event__ - Event
- __Medal__ - Gold, Silver, Bronze, or NA

In [1]:
import pandas as pd

In [2]:
# Change the path to the dataset file if needed. 
PATH = '../../data/athlete_events.csv'

In [3]:
data = pd.read_csv(PATH)
data.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

__1. How old were the youngest male and female participants of the 1996 Olympics?__

- 16 and 15
- 14 and 12 
- 16 and 12
- 13 and 11

In [23]:
data.groupby(['Sex',(data['Year'] == 1996)])['Age'].describe()

              count       mean       std   min   25%   50%   75%   max
Sex Year
F   False   69092.0  23.738523  5.798434  11.0  20.0  23.0  27.0  74.0
    True     5006.0  23.655014  5.751171  12.0  19.0  23.0  27.0  58.0
M   False  178778.0  26.309087  6.528738  10.0  22.0  25.0  29.0  97.0
    True     8766.0  25.634611  5.218781  14.0  22.0  25.0  28.0  63.0

__2. What was the percentage of male gymnasts among all the male participants of the 2000 Olympics? Round the answer to the first decimal.__

*Hint:* here and further if needed drop duplicated sportsmen to count only unique ones. 

- 0.2
- 1.5 
- 2.5
- 7.7

In [25]:
data.sort_values('Name')

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
1560,869,"Gabrielle Marie ""Gabby"" Adcock (White-)",F,25.0,167.0,NaN,Great Britain,GBR,2016 Summer,2016,Summer,Rio de Janeiro,Badminton,Badminton Mixed Doubles,NaN
215054,107953,Eleonora Margarida Josephina Scmitt,F,16.0,NaN,NaN,Brazil,BRA,1948 Summer,1948,Summer,London,Swimming,Swimming Women's 100 metres Freestyle,NaN
215055,107953,Eleonora Margarida Josephina Scmitt,F,16.0,NaN,NaN,Brazil,BRA,1948 Summer,1948,Summer,London,Swimming,Swimming Women's 4 x 100 metres Freestyle Relay,NaN
92099,46661,Jean Hauptmanns,M,26.0,NaN,NaN,Germany,GER,1912 Summer,1912,Summer,Stockholm,Wrestling,"Wrestling Men's Heavyweight, Greco-Roman",NaN
51334,26388,Luis ngel Fernando de los Santos Grossi,M,23.0,NaN,NaN,Uruguay,URU,1948 Summer,1948,Summer,London,Cycling,"Cycling Men's Team Pursuit, 4,000 metres",NaN
51336,26388,Luis ngel Fernando de los Santos Grossi,M,27.0,NaN,NaN,Uruguay,URU,1952 Summer,1952,Summer,Helsinki,Cycling,"Cycling Men's Road Race, Team",NaN
51337,26388,Luis ngel Fernando de los Santos Grossi,M,27.0,NaN,NaN,Uruguay,URU,1952 Summer,1952,Summer,Helsinki,Cycling,"Cycling Men's 1,000 metres Time Trial",NaN
51338,26388,Luis ngel Fernando de los Santos Grossi,M,27.0,NaN,NaN,Uruguay,URU,1952 Summer,1952,Summer,Helsinki,Cycling,"Cycling Men's Team Pursuit, 4,000 metres",NaN
51335,26388,Luis ngel Fernando de los Santos Grossi,M,27.0,NaN,NaN,Uruguay,URU,1952 Summer,1952,Summer,Helsinki,Cycling,"Cycling Men's Road Race, Individual",NaN
58301,29842,Th Anh,F,20.0,165.0,58.0,Vietnam,VIE,2016 Summer,2016,Summer,Rio de Janeiro,Fencing,"Fencing Women's Foil, Individual",NaN
58302,29843,Th Ngn Thng,F,19.0,147.0,47.0,Vietnam,VIE,2008 Summer,2008,Summer,Beijing,Gymnastics,Gymnastics Women's Individual All-Around,NaN
58305,29843,Th Ngn Thng,F,19.0,147.0,47.0,Vietnam,VIE,2008 Summer,2008,Summer,Beijing,Gymnastics,Gymnastics Women's Uneven Bars,NaN
58304,29843,Th Ngn Thng,F,19.0,147.0,47.0,Vietnam,VIE,2008 Summer,2008,Summer,Beijing,Gymnastics,Gymnastics Women's Horse Vault,NaN
58306,29843,Th Ngn Thng,F,19.0,147.0,47.0,Vietnam,VIE,2008 Summer,2008,Summer,Beijing,Gymnastics,Gymnastics Women's Balance Beam,NaN
58307,29843,Th Ngn Thng,F,23.0,147.0,47.0,Vietnam,VIE,2012 Summer,2012,Summer,London,Gymnastics,Gymnastics Women's Uneven Bars,NaN
58308,29843,Th Ngn Thng,F,23.0,147.0,47.0,Vietnam,VIE,2012 Summer,2012,Summer,London,Gymnastics,Gymnastics Women's Balance Beam,NaN
58303,29843,Th Ngn Thng,F,19.0,147.0,47.0,Vietnam,VIE,2008 Summer,2008,Summer,Beijing,Gymnastics,Gymnastics Women's Floor Exercise,NaN
58309,29844,Tin Tun,M,21.0,173.0,63.0,Vietnam,VIE,1988 Summer,1988,Summer,Seoul,Boxing,Boxing Men's Welterweight,NaN
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
153340,76959,A. Aanantha Sambu Mayavo,M,26.0,NaN,NaN,Malaysia,MAS,1992 Summer,1992,Summer,Barcelona,Hockey,Hockey Men's Hockey,NaN
528,300,A. Abdul Razzak,M,NaN,178.0,70.0,Iraq,IRQ,1960 Summer,1960,Summer,Roma,Athletics,Athletics Men's Long Jump,NaN
529,300,A. Abdul Razzak,M,NaN,178.0,70.0,Iraq,IRQ,1960 Summer,1960,Summer,Roma,Athletics,Athletics Men's Triple Jump,NaN
4015,2316,A. Albert,M,NaN,NaN,NaN,Union des Socits Franais de Sports Athletiques,FRA,1900 Summer,1900,Summer,Paris,Rugby,Rugby Men's Rugby,Gold
30535,15740,A. Brun,F,NaN,NaN,NaN,France,FRA,1900 Summer,1900,Summer,Paris,Golf,Golf Women's Individual,NaN
33013,16990,A. Buydens,M,NaN,NaN,NaN,Belgium,BEL,1924 Summer,1924,Summer,Paris,Swimming,Swimming Men's 4 x 200 metres Freestyle Relay,NaN
221808,111485,A. Charles Six,M,NaN,NaN,NaN,France,FRA,1928 Summer,1928,Summer,Amsterdam,Hockey,Hockey Men's Hockey,NaN
41377,21337,A. Christory,M,NaN,NaN,NaN,France,FRA,1924 Summer,1924,Summer,Paris,Art Competitions,Art Competitions Mixed Literature,NaN
49292,25390,A. Darnis,M,NaN,NaN,NaN,France,FRA,1900 Summer,1900,Summer,Paris,Shooting,Shooting Men's Trap,NaN
59127,30274,A. Dubois,M,NaN,NaN,NaN,Gitana-2,FRA,1900 Summer,1900,Summer,Paris,Sailing,Sailing Mixed 3-10 Ton,Bronze
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106609,53917,ystein Jarlsbo,M,22.0,181.0,83.0,Norway,NOR,1984 Winter,1984,Winter,Sarajevo,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
156249,78469,ystein Mellerud,M,25.0,NaN,NaN,Norway,NOR,1964 Winter,1964,Winter,Innsbruck,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
176871,88929,ystein Olsen,M,23.0,177.0,94.0,Norway,NOR,1992 Winter,1992,Winter,Albertville,Ice Hockey,Ice Hockey Men's Ice Hockey,NaN
187460,94217,ystein Pettersen,M,27.0,181.0,83.0,Norway,NOR,2010 Winter,2010,Winter,Vancouver,Cross Country Skiing,Cross Country Skiing Men's Sprint,NaN
187461,94217,ystein Pettersen,M,27.0,181.0,83.0,Norway,NOR,2010 Winter,2010,Winter,Vancouver,Cross Country Skiing,Cross Country Skiing Men's Team Sprint,Gold
222872,111941,ystein Slettemark,M,42.0,188.0,80.0,Denmark,DEN,2010 Winter,2010,Winter,Vancouver,Biathlon,Biathlon Men's 20 kilometres,NaN
222871,111941,ystein Slettemark,M,42.0,188.0,80.0,Denmark,DEN,2010 Winter,2010,Winter,Vancouver,Biathlon,Biathlon Men's 10 kilometres Sprint,NaN
19724,10403,yvind Berg,M,22.0,185.0,73.0,Norway,NOR,1994 Winter,1994,Winter,Lillehammer,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
19722,10403,yvind Berg,M,22.0,185.0,73.0,Norway,NOR,1994 Winter,1994,Winter,Lillehammer,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN
19720,10403,yvind Berg,M,20.0,185.0,73.0,Norway,NOR,1992 Winter,1992,Winter,Albertville,Ski Jumping,"Ski Jumping Men's Normal Hill, Individual",NaN
19723,10403,yvind Berg,M,22.0,185.0,73.0,Norway,NOR,1994 Winter,1994,Winter,Lillehammer,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
19721,10403,yvind Berg,M,20.0,185.0,73.0,Norway,NOR,1992 Winter,1992,Winter,Albertville,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
245408,122902,yvind Tveter,M,25.0,190.0,89.0,Norway,NOR,1980 Winter,1980,Winter,Lake Placid,Speed Skating,"Speed Skating Men's 5,000 metres",NaN
245409,122902,yvind Tveter,M,25.0,190.0,89.0,Norway,NOR,1980 Winter,1980,Winter,Lake Placid,Speed Skating,"Speed Skating Men's 10,000 metres",NaN
61346,31417,zcan Ediz,M,17.0,NaN,NaN,Turkey,TUR,1992 Summer,1992,Summer,Barcelona,Archery,Archery Men's Team,NaN
61345,31417,zcan Ediz,M,17.0,NaN,NaN,Turkey,TUR,1992 Summer,1992,Summer,Barcelona,Archery,Archery Men's Individual,NaN
2857,1587,zdemir Akbal,M,23.0,178.0,58.0,Turkey,TUR,2000 Summer,2000,Summer,Sydney,Archery,Archery Men's Individual,NaN
2858,1587,zdemir Akbal,M,23.0,178.0,58.0,Turkey,TUR,2000 Summer,2000,Summer,Sydney,Archery,Archery Men's Team,NaN
65654,33596,zden Ezinler,F,22.0,166.0,50.0,Turkey,TUR,1972 Summer,1972,Summer,Munich,Fencing,"Fencing Women's Foil, Individual",NaN
10589,5787,zer Atei,M,25.0,180.0,72.0,Turkey,TUR,1968 Winter,1968,Winter,Grenoble,Alpine Skiing,Alpine Skiing Men's Slalom,NaN
10588,5787,zer Atei,M,25.0,180.0,72.0,Turkey,TUR,1968 Winter,1968,Winter,Grenoble,Alpine Skiing,Alpine Skiing Men's Giant Slalom,NaN
10587,5787,zer Atei,M,25.0,180.0,72.0,Turkey,TUR,1968 Winter,1968,Winter,Grenoble,Alpine Skiing,Alpine Skiing Men's Downhill,NaN
16645,8931,zge Bayrak,F,24.0,166.0,60.0,Turkey,TUR,2016 Summer,2016,Summer,Rio de Janeiro,Badminton,Badminton Women's Singles,NaN
119868,60685,zge Krdar emberci,F,27.0,183.0,70.0,Turkey,TUR,2012 Summer,2012,Summer,London,Volleyball,Volleyball Women's Volleyball,NaN
114964,58232,zlem Kaya,F,22.0,165.0,47.0,Turkey,TUR,2012 Summer,2012,Summer,London,Athletics,"Athletics Women's 3,000 metres Steeplechase",NaN
114965,58232,zlem Kaya,F,26.0,165.0,47.0,Turkey,TUR,2016 Summer,2016,Summer,Rio de Janeiro,Athletics,"Athletics Women's 3,000 metres Steeplechase",NaN
79870,40545,zman Graud,M,33.0,168.0,72.0,Turkey,TUR,1972 Summer,1972,Summer,Munich,Shooting,Shooting Mixed Skeet,NaN
207676,104222,zzet Safer,M,26.0,178.0,74.0,Turkey,TUR,2016 Summer,2016,Summer,Rio de Janeiro,Athletics,Athletics Men's 4 x 100 metres Relay,NaN
102955,52087,zzet nce,M,23.0,172.0,85.0,Turkey,TUR,2004 Summer,2004,Summer,Athina,Weightlifting,Weightlifting Men's Light-Heavyweight,NaN
102956,52087,zzet nce,M,27.0,172.0,85.0,Turkey,TUR,2008 Summer,2008,Summer,Beijing,Weightlifting,Weightlifting Men's Light-Heavyweight,NaN

__3. What are the mean and standard deviation of height for female basketball players participated in the 2000 Olympics? Round the answer to the first decimal.__

- 178.5 and 7.2
- 179.4 and 10
- 180.7 and 6.7
- 182.4 and 9.1

In [6]:
# You code here

__4. Find a sportsperson participated in the 2002 Olympics, with the highest weight among other participants of the same Olympics. What sport did he or she do?__

- Judo
- Bobsleigh 
- Weightlifting
- Boxing

In [7]:
# You code here

__5. How many times did Pawe Abratkiewicz participate in the Olympics held in different years?__

- 0
- 1 
- 2
- 3

In [8]:
# You code here

__6. How many silver medals in tennis did Australia win at the 2000 Olympics?__

- 0
- 1 
- 2 
- 3

In [9]:
# You code here

__7. Is it true that Switzerland won fewer medals than Serbia at the 2016 Olympics? Do not consider NaN values in _Medal_ column.__ 

- Yes 
- No

In [10]:
# You code here

__8. What age category did the fewest and the most participants of the 2014 Olympics belong to?__
- [45-55] and [25-35) correspondingly
- [45-55] and [15-25) correspondingly
- [35-45] and [25-35) correspondingly
- [45-55] and [35-45) correspondingly

In [11]:
# You code here

__9. Is it true that there were Summer Olympics held in Lake Placid? Is it true that there were Winter Olympics held in Sankt Moritz?__

- Yes, Yes
- Yes, No
- No, Yes 
- No, No

In [12]:
# You code here

__10. What is the absolute difference between the number of unique sports at the 1995 Olympics and 2016 Olympics?__

- 16
- 24
- 26
- 34

In [13]:
# You code here